---
new_page_extension: md
auto_deploy: false
admin_path: src/admin
webhook_url: https://api.netlify.com/build_hooks/60436d484813f70c0460ff7a
sections:
- type: directory
  path: src/content/en/articles
  label: Articles EN
  create: documents
  match: "**/*"
  exclude: "**/*.json"
  templates:
  - post
- type: directory
  path: src/content/pt/articles
  label: Artigos PT
  create: documents
  match: "**/*"
  exclude: "**/*.json"
  templates:
  - post
upload_dir: ''
public_path: https://res.cloudinary.com/fabiomrbarbosa
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
