backend:
  name: github
  repo: fabiomrbarbosa/fabiomrbarbosa.com
  branch: main
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: fabiomrbarbosa
    api_key: 528922696965761
i18n:
  structure: multiple_folders
  locales: [en, pt]

collections:
  - name: articles
    label: Articles
    folder: src/content/articles
    create: true
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Translation Key
        name: translationKey
        widget: string
        i18n: duplicate
      - label: Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Tags
        name: tags
        widget: list
        i18n: true
      - label: Featured?
        name: featured
        widget: boolean
        default: false
        i18n: true
      - label: Status
        name: status
        widget: "select"
        options:
          - { label: "Seedling", value: "seedling" }
          - { label: "Budding", value: "budding" }
          - { label: "Evergreen", value: "evergreen" }
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
